# Generated by Django 4.2.3 on 2024-12-08 00:15

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=profile.models.get_default_profile_image, null=True, upload_to=profile.models.get_profile_image_filepath),
        ),
    ]
