# Generated by Django 4.2.3 on 2024-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_blog_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-07 10:00'),
            preserve_default=False,
        ),
    ]
